version: '3'

services:
  pytest_db:
    image: postgres:17
    container_name: pytest_db
    env_file: 
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}  
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    ports: 
      - ${TEST_DB_PORT}:5432
    volumes:
      - pytest_db:/var/lib/postgresql/data
    networks:
      - pytest_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  pytest_db:
    name: pytest_db

networks:
  pytest_network:
    name: pytest_network
