"""2024_12_02_9cf52a09

Revision ID: e4d75cf3a1a7
Revises: 620478159033
Create Date: 2024-12-02 00:16:13.501170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4d75cf3a1a7"
down_revision: Union[str, None] = "620478159033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        schema="booking",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin", schema="booking")
    # ### end Alembic commands ###
